FROM node:20-alpine

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install --production

COPY dist/apps/verifactu-worker ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]