sonar.projectKey=josanz-erp
sonar.organization=josanz
sonar.projectName=Josanz ERP

sonar.sources=apps,libs
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts
sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/apps/*/lcov.info
sonar.testExecutionReportPaths=test-report.xml