const { createGlobPatternsForDependencies } = require('@nx/angular/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        brand: 'var(--brand)',
        // Background colors
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        // Surface colors
        surface: 'var(--surface)',
        'surface-hover': 'var(--surface-hover)',
        // Text colors
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        // Accent colors
        accent: 'var(--accent)',
        'accent-muted': 'var(--accent-muted)',
        // Status colors
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        info: 'var(--info)',
        // Border colors
        'border-soft': 'var(--border-soft)',
        'border-vibrant': 'var(--border-vibrant)',
        // Legacy mappings for compatibility
        white: 'var(--bg-secondary)',
        black: 'var(--text-primary)',
        gray: {
          50: 'var(--bg-secondary)',
          100: 'var(--surface)',
          200: 'var(--border-soft)',
          300: 'var(--border-soft)',
          400: 'var(--text-secondary)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
        },
        slate: {
          50: 'var(--bg-secondary)',
          100: 'var(--surface)',
          200: 'var(--border-soft)',
          300: 'var(--border-soft)',
          400: 'var(--text-secondary)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
        },
        blue: {
          50: 'var(--brand-ambient)',
          100: 'var(--brand-surface)',
          200: 'var(--brand-border-soft)',
          300: 'var(--brand)',
          400: 'var(--brand)',
          500: 'var(--brand)',
          600: 'var(--brand)',
          700: 'var(--brand)',
          800: 'var(--brand)',
          900: 'var(--brand)',
        },
        green: {
          50: 'color-mix(in srgb, var(--success) 10%, var(--bg-secondary))',
          100: 'color-mix(in srgb, var(--success) 20%, var(--bg-secondary))',
          200: 'color-mix(in srgb, var(--success) 30%, var(--bg-secondary))',
          300: 'color-mix(in srgb, var(--success) 40%, var(--bg-secondary))',
          400: 'color-mix(in srgb, var(--success) 50%, var(--bg-secondary))',
          500: 'var(--success)',
          600: 'var(--success)',
          700: 'var(--success)',
          800: 'var(--success)',
          900: 'var(--success)',
        },
        red: {
          50: 'color-mix(in srgb, var(--danger) 10%, var(--bg-secondary))',
          100: 'color-mix(in srgb, var(--danger) 20%, var(--bg-secondary))',
          200: 'color-mix(in srgb, var(--danger) 30%, var(--bg-secondary))',
          300: 'color-mix(in srgb, var(--danger) 40%, var(--bg-secondary))',
          400: 'color-mix(in srgb, var(--danger) 50%, var(--bg-secondary))',
          500: 'var(--danger)',
          600: 'var(--danger)',
          700: 'var(--danger)',
          800: 'var(--danger)',
          900: 'var(--danger)',
        },
        indigo: {
          50: 'var(--brand-ambient)',
          100: 'var(--brand-surface)',
          200: 'var(--brand-border-soft)',
          300: 'var(--brand)',
          400: 'var(--brand)',
          500: 'var(--brand)',
          600: 'var(--brand)',
          700: 'var(--brand)',
          800: 'var(--brand)',
          900: 'var(--brand)',
        },
        emerald: {
          50: 'color-mix(in srgb, var(--success) 10%, var(--bg-secondary))',
          100: 'color-mix(in srgb, var(--success) 20%, var(--bg-secondary))',
          200: 'color-mix(in srgb, var(--success) 30%, var(--bg-secondary))',
          300: 'color-mix(in srgb, var(--success) 40%, var(--bg-secondary))',
          400: 'color-mix(in srgb, var(--success) 50%, var(--bg-secondary))',
          500: 'var(--success)',
          600: 'var(--success)',
          700: 'var(--success)',
          800: 'var(--success)',
          900: 'var(--success)',
        },
      },
      backgroundColor: {
        primary: 'var(--bg-primary)',
        secondary: 'var(--bg-secondary)',
        tertiary: 'var(--bg-tertiary)',
        surface: 'var(--surface)',
        'surface-hover': 'var(--surface-hover)',
      },
      textColor: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        muted: 'var(--text-muted)',
      },
      borderColor: {
        soft: 'var(--border-soft)',
        vibrant: 'var(--border-vibrant)',
      },
      ringColor: {
        focus: 'var(--ring-focus)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        glow: 'var(--shadow-glow)',
        'inset-shine': 'var(--shadow-inset-shine)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      fontFamily: {
        main: 'var(--font-main)',
        display: 'var(--font-display)',
        gaming: 'var(--font-gaming)',
        retro: 'var(--font-retro)',
        tech: 'var(--font-tech)',
        clean: 'var(--font-clean)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        base: 'var(--transition-base)',
        spring: 'var(--transition-spring)',
      },
    },
  },
  plugins: [],
};
