import {
  ApplicationConfig,
  provideZoneChangeDetection,
  importProvidersFrom,
  APP_INITIALIZER,
  inject,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { appRoutes } from './app.routes';
import {
  authInterceptor,
  tenantInterceptor,
  AuthService,
  AuthStore,
  TenantModulesApiService,
  TenantModulesRealtimeService,
  TENANT_MODULES_REALTIME_API_ORIGIN,
  getStoredTenantId,
  syncErpTenantHtmlTheme,
} from '@josanz-erp/identity-data-access';
import { GlobalAuthStore, PluginStore } from '@josanz-erp/shared-data-access';
import { firstValueFrom, catchError, of, tap } from 'rxjs';
import { apiOriginInterceptor } from './api-origin.interceptor';
import { verifactuApiKeyInterceptor } from './verifactu-api-key.interceptor';
import {
  User,
  Lock,
  ArrowRight,
  LucideAngularModule,
  Search,
  Building2,
  Bell,
  LayoutDashboard,
  Layout,
  Users,
  Package,
  Receipt,
  Truck,
  Car,
  Key,
  History,
  Menu,
  ChevronLeft,
  Settings,
  LogOut,
  Pencil,
  Trash2,
  Eye,
  Play,
  Check,
  X,
  CirclePlus,
  ArrowUp,
  FileText,
  FileCheck,
  Download,
  Sun,
  Moon,
  Send,
  ShieldCheck,
  QrCode,
  Save,
  TriangleAlert,
  Mail,
  Slash,
  TrendingUp,
  CircleAlert,
  BellOff,
  Clock,
  RefreshCw,
  Construction,
  Cog,
  ArrowLeft,
  SearchX,
  FilePlus,
  UserPlus,
  Hash,
  IdCard,
  Calendar,
  CalendarClock,
  CalendarPlus,
  Euro,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  EllipsisVertical,
  MoreHorizontal,
  CirclePlay,
  CalendarCheck,
  Box,
  Briefcase,
  ChartPie,
  SquareCheck,
  PenTool,
  RotateCcw,
  DollarSign,
  Archive,
  Shield,
  OctagonAlert,
  BarChart3,
  BarChart2,
  Layers,
  Wrench,
  Activity,
  Camera,
  Clapperboard,
  Info,
  Tag,
  Puzzle,
  SlidersHorizontal,
  Sliders,
  Settings2,
  FileX,
  CloudUpload,
  Printer,
  Timer,
  FileUp,
  Wallet,
  HelpCircle,
  Keyboard,
  Phone,
  Smartphone,
  MapPin,
  Sparkles,
  Inbox,
  Gauge,
  UserCheck,
  Filter,
  Copy,
  Star,
  CreditCard,
  ChartLine,
  PartyPopper,
  Presentation,
  ExternalLink,
  Bot,
  CircleCheck,
  Cpu,
  GripVertical,
  Mic,
  MicOff,
  Smile,
  Zap,
  Minus,
  FlaskConical,
  Globe,
  Volume2,
  BarChart,
  CheckCircle,
  Banknote,
  CheckCheck,
  UploadCloud,
  RotateCw,
  AlertTriangle,
  Navigation,
  AlertCircle,
  CheckSquare,
  AlertOctagon,
  StickyNote,
  Palette,
  ShieldOff,
  UserX,
  Plus,
  ShieldAlert,
  Calculator,
  WifiOff,
  CloudOff,
  CalendarDays,
  CircleUser,
  CircleX,
  CircleCheckBig,
  BrainCircuit,
  Shrink,
  Maximize2,
  Expand,
} from 'lucide-angular';
import { VERIFACTU_API_BASE_URL } from '@josanz-erp/verifactu-api';
import { environment } from '../environments/environment';

export const appConfig: ApplicationConfig = {
  providers: [
    /** Antes de cualquier tema: marca `data-erp-tenant` desde session (babooni → Biosstel). */
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory: () => () => {
        syncErpTenantHtmlTheme();
      },
    },
    {
      provide: TENANT_MODULES_REALTIME_API_ORIGIN,
      useFactory: () => environment.apiOrigin?.replace(/\/$/, '') ?? '',
    },
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(appRoutes),
    provideHttpClient(
      withInterceptors([
        apiOriginInterceptor,
        verifactuApiKeyInterceptor,
        tenantInterceptor,
        authInterceptor,
      ]),
    ),
    {
      provide: APP_INITIALIZER,
      useFactory: () => {
        const authService = inject(AuthService);
        const globalAuthStore = inject(GlobalAuthStore);
        const tenantModulesApi = inject(TenantModulesApiService);
        const tenantModulesRealtime = inject(TenantModulesRealtimeService);
        const authStore = inject(AuthStore);
        const pluginStore = inject(PluginStore);
        tenantModulesRealtime.registerIdentityRefresh(() => {
          authStore.refreshSession();
        });
        return async () => {
          const token = localStorage.getItem('auth_token');
          if (!token) {
            pluginStore.loadFromStorage();
            return;
          }
          try {
            const response = await firstValueFrom(
              authService.refreshSession().pipe(catchError(() => of(null)))
            );
            if (response) {
              authService.setToken(response.accessToken);
              if (response.tenantId) {
                authService.setTenantId(response.tenantId);
              }
              const u = response.user;
              const displayName = [u.firstName, u.lastName].filter(Boolean).join(' ').trim() || u.email;
              globalAuthStore.setUser({
                id: u.id,
                email: u.email,
                name: displayName,
                tenantId: response.tenantId || getStoredTenantId() || '',
                permissions: u.permissions,
              });
              await firstValueFrom(
                tenantModulesApi.fetchEnabledModules().pipe(
                  tap((r) => pluginStore.setPlugins(r.enabledModuleIds)),
                  catchError(() => {
                    pluginStore.loadFromStorage();
                    return of(null);
                  })
                )
              );
              tenantModulesRealtime.connect(
                environment.apiOrigin?.replace(/\/$/, '') ?? '',
              );
            } else {
              pluginStore.loadFromStorage();
            }
          } catch {
            pluginStore.loadFromStorage();
          }
        };
      },
      multi: true,
    },
    importProvidersFrom(
      LucideAngularModule.pick({
        User,
        Lock,
        ArrowRight,
        Search,
        Building2,
        Bell,
        LayoutDashboard,
        Layout,
        Users,
        Package,
        Receipt,
        Truck,
        Car,
        Key,
        History,
        Menu,
        ChevronLeft,
        Settings,
        LogOut,
        Pencil,
        Trash2,
        Eye,
        Play,
        Check,
        X,
        CirclePlus,
        ArrowUp,
        FileText,
        FileCheck,
        Download,
        Sun,
        Moon,
        Send,
        ShieldCheck,
        QrCode,
        Save,
        TriangleAlert,
        Mail,
        Slash,
        TrendingUp,
        CircleAlert,
        BellOff,
        Clock,
        RefreshCw,
        Construction,
        Cog,
        ArrowLeft,
        SearchX,
        FilePlus,
        UserPlus,
        Hash,
        IdCard,
        Calendar,
        CalendarClock,
        CalendarPlus,
        Euro,
        ChevronRight,
        ChevronDown,
        ChevronUp,
        EllipsisVertical,
        MoreHorizontal,
        CirclePlay,
        CalendarCheck,
        Box,
        Briefcase,
        ChartPie,
        SquareCheck,
        PenTool,
        RotateCcw,
        DollarSign,
        Archive,
        Shield,
        OctagonAlert,
        BarChart3,
        BarChart2,
        Layers,
        Wrench,
        Activity,
        Camera,
        Clapperboard,
        Info,
        Tag,
        Puzzle,
        SlidersHorizontal,
        Sliders,
        Settings2,
        FileX,
        CloudUpload,
        Printer,
        Timer,
        FileUp,
        Wallet,
        HelpCircle,
        Keyboard,
        Phone,
        Smartphone,
        MapPin,
        Sparkles,
        Inbox,
        Gauge,
        UserCheck,
        Filter,
        Copy,
        Star,
        CreditCard,
        ChartLine,
        PartyPopper,
        Presentation,
        ExternalLink,
        Bot,
        CircleCheck,
        Cpu,
        GripVertical,
        Mic,
        MicOff,
        Smile,
        Zap,
        Minus,
        FlaskConical,
        Globe,
        Volume2,
        BarChart,
        CheckCircle,
        Banknote,
        CheckCheck,
        UploadCloud,
        RotateCw,
        AlertTriangle,
        Navigation,
        AlertCircle,
        CheckSquare,
        AlertOctagon,
        StickyNote,
        Palette,
        ShieldOff,
        UserX,
        Plus,
        ShieldAlert,
        Calculator,
        WifiOff,
        CloudOff,
        CalendarDays,
        CircleUser,
        CircleX,
        CircleCheckBig,
        BrainCircuit,
        Shrink,
        Maximize2,
        Expand,
      }),
    ),
    { provide: VERIFACTU_API_BASE_URL, useValue: 'http://localhost:3110/api' },
  ],
};
